# Generated by Django 4.1.13 on 2025-04-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('cholesterol_level', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_sugar', models.CharField(blank=True, max_length=20, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('existing_conditions', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('smoker', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise_intensity', models.CharField(blank=True, max_length=50, null=True)),
                ('diet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=50, null=True)),
                ('water_intake', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_health_assessment', models.TextField()),
                ('potential_health_issues', models.TextField()),
                ('risk_minimization_recommendations', models.TextField()),
                ('full_analysis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='health_analyzer.healthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='health_analyzer.healthanalysis')),
            ],
        ),
    ]
